version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8207:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    image: devsamuel1227/backend:latest
    depends_on:
      - mysql
    ports:
      - "8206:8206"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASS: password
      DB_NAME: mydb
    restart: unless-stopped

  frontend:
    image: devsamuel1227/frontend:latest
    depends_on:
      - backend
    ports:
      - "8208:80"
    restart: unless-stopped

volumes:
  mysql_data: