version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: meubanco
    ports:
      - "5433:5432"
    networks:
      - meuappnet
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "8206:3000"
    networks:
      - meuappnet

networks:
  meuappnet:

volumes:
  pgdata:
