name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: CI/CD Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar acesso SSH ao servidor remoto
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/projeto-vollo:latest .

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push da imagem para o Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/projeto-vollo:latest

      - name: Executar análise com SonarQube via SSH
        run: |
          ssh -o StrictHostKeyChecking=no aluno@201.23.3.86 << 'EOF'
            docker run -d --name sonar -p 9000:9000 sonarqube:latest
            echo "Aguardando SonarQube iniciar..."
            sleep 60
            cd /home/aluno/EntregaContinua/backend
            sonar-scanner \
              -Dsonar.projectKey=projeto-vollo \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://localhost:9000 \
              -Dsonar.login=admin \
              -Dsonar.password=admin
            RESULT=$?
            docker stop sonar && docker rm sonar
            if [ $RESULT -ne 0 ]; then
              echo "Falha na análise do SonarQube"
              exit 1
            fi
          EOF

      - name: Deploy remoto via SSH
        run: |
          ssh -o StrictHostKeyChecking=no aluno@201.23.3.86 << 'EOF'
            docker stop projeto-vollo || true
            docker rm projeto-vollo || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/projeto-vollo:latest
            docker run -d \
              --name projeto-vollo \
              -p 8206:3000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/projeto-vollo:latest
          EOF
